### PR TITLE
The lost logo

### PR DESCRIPTION
**Pull request by aniewielska**
I replaced the missing logo with the current one from GA4GH website, but not sure, if this is the best solution. It fixes the problem, but the logo may well disappear again.

### CODE REVIEW

**Comment by kellrott** [comment]
LGTM

**Review by kellrott — APPROVED** [review]

**Comment by rishidev** [comment]
GA4GH Comms has suggested using https://ga4gh.org/wp-content/uploads/GA-logo-horizontal-RGB-1400.png
The other files are from the template theme. If the SVG is preferred that could also be uploaded instead I guess.

**Comment by rishidev** [comment]
The permalink for the logo has now been confirmed as https://w3id.org/ga4gh/ga4gh-logo.svg

**Comment by aniewielska** [comment]
At the moment the old logo is working fine, but I replaced the link used in this PR with the permalink anyway.

**Comment by rishidev** [comment]
Thanks, this will future proof this.

**Pull request merged**
