### PR TITLE
Implementing GA4GH service-info for TES

### LINKED ISSUE #128: Implement GA4GH service-info for TES
Enables service discovery. 

Update: [ga4gh-discovery/ga4gh-service-info#how-to-use-and-extend-this-specification](https://github.com/ga4gh-discovery/ga4gh-service-info#how-to-use-and-extend-this-specification)

Suggestion in workstream call is to create a PR but leave it pending discussion of loose ends

### PR DESCRIPTION
**Pull request by susheel**
Following instructions https://github.com/ga4gh-discovery/ga4gh-service-info#how-to-use-and-extend-this-specification

This introduces breaking changes:
- d432788 /tasks/service-info does not exist 
- 6b3af5d /service-info new endpoint 
- [ ] Bump OAPI from 2 to 3
- [ ] Merge storage array dict with GA4GH service-info spec

Resolves #128

### CODE REVIEW

**Comment by susheel** [comment]
Rebased this to release/v0.4.1

**Comment by delagoya** [comment]
Original TES service info included extra information, namely the types of storage URI schemes supported by the endpoint. We may need to extend the ServiceInfo definition as per https://github.com/ga4gh-discovery/ga4gh-service-info#extending-service-info-payloads

**Comment by susheel** [comment]
@delagoya Noted. I have added these as tasks in the description.

**Comment by susheel** [comment]
GA4GH service-info has just tagged their release [v1.0.0](https://github.com/ga4gh-discovery/ga4gh-service-info/releases/tag/v1.0.0) which is now updated in the PR.

Merge with existing TES dict needs planning

**Comment by aniewielska** [comment]
GA4GH service-info has been in the end implemented in TES in #132 together with OpenAPI 3 migration and changed further in #143. Thanks for starting this effort here.

**Pull request closed without merging**
