### PR TITLE
Revert "OAPI 2.0 Swagger YAML"

### PR DESCRIPTION
**Pull request by susheel**
Reverts ga4gh/task-execution-schemas#113 just so that the community is notified before eventual merge into master.

### CODE REVIEW

**Comment by delagoya** [comment]
Before you merge this request, see the note from issue #113 about rebasing master to ish 0765b930542ebd8124d5b42109fe81916129f99c 

Is that preferable to re-adding files?

**Comment by susheel** [comment]
@delagoya I can't see a way to rebase this to 0765b93 as the commits have already been pushed and merged.

I would merge this into master. We have all the new changes in `develop` anyway.

**Comment by delagoya** [comment]
It should be possible to rebase local and force-push to origin/master but that may confuse folks that have already pulled down the most recent branch. Let’s just go ahead and apply the revert changes.

**Comment by susheel** [comment]
@delagoya Yes, exactly. Reverting changes.

**Pull request merged**
