### PR TITLE
OAPI 2.0 Swagger YAML

### PR DESCRIPTION
**Pull request by susheel**
Converted Swagger JSON into YAML help with future updates and fixes.
Starting work towards #109 and beyond

### CODE REVIEW

**Comment by susheel** [comment]
TODO: Still have to sanity check the required and optional  attributes of the models

**Comment by delagoya** [comment]
Two issues:

1. remove the JSON if the YAML is the canonical version. 
2. Looks like this PR implicitly approves #105 . Will need community comment and approve on that before merging.

**Comment by susheel** [comment]
@delagoya 
1. https://github.com/ga4gh/task-execution-schemas/pull/113/commits/c61942d26647eb77372c64de5cfc665f8580b2d1 removes the JSON spec
2. Yes, it does. I can split this out into a separate pull so this would be easier to merge.

**Comment by delagoya** [comment]
Right. Will revert master. Can we safely push this to develop branch?

**Comment by delagoya** [comment]
Or actually these are already in the new `develop` branch.

**Comment by delagoya** [comment]
Suggest we rebase `master` to `0765b930542` ish instead of a separate PR that reverts changes as new commits.

**Pull request merged**
