### PR TITLE
TES 0.4.0 Release

### PR DESCRIPTION
**Pull request by susheel**
Task Execution Service 0.4.0 Release

**Summary:**
- Conversion of `task_execution.swagger.json` into OAPI 2.0 YAML
- Cleanup of `required` and `optional` fields for OAPI request/response schema

**Breaking Changes:**
- Schema location `task_schema.swagger.json` updated to `openapi/task_schema.swagger.yaml`
- `required` fields are now explicit in the schema.

### CODE REVIEW

**Comment by briandoconnor** [comment]
Susheel and Angel think this will be sufficient for the April meeting.

**Comment by MattMcL4475** [comment]
@susheel @delagoya @briandoconnor Hi guys, are you still planning on merging this with master?

**Comment by susheel** [comment]
LGTM

**Comment by delagoya** [comment]
+1 

Also LGTM

**Comment by delagoya** [comment]
There are merge conflicts though. @denis-yuen do you think these changes should be merged?

**Comment by denis-yuen** [comment]
@delagoya looks like git was just confused because  `task_schema.swagger.json` was deleted and reverted previously in master. 

Assuming `openapi/task_schema.swagger.yaml` is correct, this LGTM

**Comment by adamstruck** [comment]
LGTM

**Pull request merged**
