### PR TITLE
OpenAPI Doc content improvements

### PR DESCRIPTION
**Pull request by kellrott**

### CODE REVIEW

**Comment by aniewielska** [comment]
Looks like we are working on the same topic. Could you possibly please have a look at #134 first and perhaps it is time to approve it? I kept `summary` items short (such as GetTask) similarly to what WES had, but I left descriptions largely intact. It should help with your work here.

**Comment by kellrott** [comment]
I've sync'd with origin/master after merging #134. 

It looks like the operation `summary` field is used to populate the overview list on the left hand side of the doc, so those should probably be kept to a single word.

**Comment by kellrott** [comment]
I've added a `Introduction` and `Standards` section to the head of the document that are a new copy/paste of the blocks found in the WES document.

**Review by aniewielska — APPROVED** [review]
LGTM (and to the OpenAPI validator, too)

**Pull request merged**
