### PR TITLE
New state

### PR DESCRIPTION
**Pull request by adamstruck**
Initializing

### CODE REVIEW

**Comment by adamstruck** [comment]
Sorry for the repeated opening and closing of this PR... The purpose for this change is so we can distinguish between when a container is running and when it is initializing (e.g. the image is being pulled).

**Comment by geoffjentry** [comment]
👍

**Comment by kellrott** [comment]
Other PRs accepts caused a collision. Please resolve conflicts so I can merge.

**Comment by adamstruck** [comment]
@kellrott done.

**Comment by kellrott** [comment]
Can you also run `make swagger` to get the docs synced?

**Pull request merged**
